/* TrackShop: no server, no payment SDK, no analytics account required.
 * Install your real GTM snippets in EACH HTML page to connect this data layer.
 * Event names use GA4 names directly (no _demo suffix). Do not add duplicate
 * GA4 click/form tags if you already send the corresponding data-layer event.
 */
'use strict';
window.dataLayer = window.dataLayer || [];
const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];
const page = document.body.dataset.page;
const money = value => new Intl.NumberFormat('en-IN', {style:'currency',currency:'INR',maximumFractionDigits:2}).format(value);
const round = value => Math.round((value + Number.EPSILON) * 100) / 100;
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PRODUCTS = [
 {item_id:'SKU001',item_name:'Running Shoes',item_category:'Footwear',price:2999,old:3499,art:0,tag:'BESTSELLER',description:'A lightweight everyday running shoe with a cushioned sole and a fresh violet accent. A fictional favorite for your analytics practice.'},
 {item_id:'SKU002',item_name:'Smart Watch',item_category:'Electronics',price:4999,old:5999,art:1,tag:'SMART PICK',description:'A clean display, a comfortable violet strap, and a little inspiration for your everyday routine. This is a demo product.'},
 {item_id:'SKU003',item_name:'Backpack',item_category:'Accessories',price:1499,old:1999,art:2,tag:'EVERYDAY ESSENTIAL',description:'A roomy everyday backpack with a simple silhouette, padded straps, and space for the things you take along. Demo item only.'},
 {item_id:'SKU004',item_name:'Wireless Headphones',item_category:'Electronics',price:3499,old:4499,art:3,tag:'FAN FAVORITE',description:'Over-ear comfort in a soft lavender finish. Build a pretend soundtrack to your day while practicing product interactions.'},
 {item_id:'SKU005',item_name:'Fitness T-Shirt',item_category:'Apparel',price:999,old:1299,art:4,tag:'EASY COMFORT',description:'An easygoing violet tee for comfortable everyday movement. A fictional product with a very real data-layer event.'},
 {item_id:'SKU006',item_name:'Water Bottle',item_category:'Accessories',price:599,old:799,art:5,tag:'TAKE IT ALONG',description:'A reusable lavender water bottle with a simple carry loop. Add a little color to your demo cart.'}
];
function readStorage(key, fallback, storage = localStorage) { try { const value = storage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } }
function saveStorage(key, value, storage = localStorage) { try { storage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } }
let cart = readStorage('trackshop-cart', []);
// Validate persisted cart data; always use prices from our catalog.
cart = Array.isArray(cart) ? PRODUCTS.flatMap(p => { const row = cart.find(x => x && x.id === p.item_id); return row && Number.isInteger(row.quantity) && row.quantity > 0 ? [{id:p.item_id,quantity:Math.min(99,row.quantity)}] : []; }) : [];
let history = readStorage('trackshop-events', [], sessionStorage);
if (!Array.isArray(history)) history = [];
let toastTimer;
function toast(message) { $('#toast').textContent = message; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').textContent = '', 3500); }
function logEvent(payload) {
 if (!payload || typeof payload.event !== 'string') return;
 try { const copy = JSON.parse(JSON.stringify(payload)); history.push({at:Date.now(),payload:copy}); history = history.slice(-80); saveStorage('trackshop-events',history,sessionStorage); renderDebug(); } catch { /* Some GTM objects cannot be serialized. Leave the GTM push untouched. */ }
}
// Observe every future push while preserving GTM's push implementation and return value.
const originalPush = window.dataLayer.push.bind(window.dataLayer);
window.dataLayer.push = function(...messages) { const result = originalPush(...messages); messages.forEach(logEvent); return result; };
function track(event, parameters = {}) { window.dataLayer.push({event,...parameters}); }
function renderDebug() {
 $('#debug-count').textContent = `${history.length} events`;
 $('#event-list').innerHTML = history.slice().reverse().map(({at,payload}) => { const {event,...params} = payload; return `<div class="event"><time>${new Date(at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><strong>${escapeHTML(event)}</strong><pre>${escapeHTML(JSON.stringify(params,null,2))}</pre></div>`; }).join('') || '<p class="debug-tip">Ready when you are. Try clicking a product.</p>';
}
$('#clear-events').addEventListener('click', () => { history=[];saveStorage('trackshop-events',history,sessionStorage);renderDebug(); });
$('#analytics-debug').open = readStorage('trackshop-debug-open', false, sessionStorage) === true;
$('#analytics-debug').addEventListener('toggle', () => saveStorage('trackshop-debug-open',$('#analytics-debug').open,sessionStorage));
renderDebug();
function item(p, quantity = 1, discount = false) { return {item_id:p.item_id,item_name:p.item_name,item_category:p.item_category,price:discount ? round(p.price * .9) : p.price,quantity,...(discount ? {discount:round(p.price*.1),coupon:'TRACK10'} : {})}; }
function cartItems(discount = false) { return cart.map(row => item(PRODUCTS.find(p => p.item_id === row.id), row.quantity, discount)); }
function sum(items) { return round(items.reduce((total,p) => total + p.price*p.quantity, 0)); }
function ecommerce(event, items, parameters = {}) {
 // Clear the previous ecommerce object so GTM does not merge stale fields.
 window.dataLayer.push({ecommerce:null});
 track(event,{ecommerce:{currency:'INR',value:sum(items),items,...parameters}});
}
function saveCart() { if (!saveStorage('trackshop-cart',cart)) toast('Browser storage is unavailable. Your cart cannot carry across pages.'); updateCount(); }
function updateCount() { $('#cart-count').textContent = cart.reduce((n,p) => n+p.quantity,0); }
function addCart(id,quantity=1,quiet=false) { const p=PRODUCTS.find(p => p.item_id===id);if(!p)return false; const row=cart.find(x=>x.id===id);const added=Math.min(99-(row?.quantity||0), Math.max(1,Math.floor(Number(quantity)||1)));if(added<=0){toast('Maximum 99 of this item per cart.');return false;}if(row) row.quantity+=added;else cart.push({id,quantity:added});saveCart();ecommerce('add_to_cart',[item(p,added)]);if(!quiet)toast(`${p.item_name} added to your cart`);return true; }
function changeQuantity(id,next) { const row=cart.find(x=>x.id===id);if(!row)return;const p=PRODUCTS.find(p=>p.item_id===id);next=Math.max(0,Math.min(99,Math.floor(Number(next)||0)));const diff=next-row.quantity;if(!diff)return;if(next===0)cart=cart.filter(x=>x.id!==id);else row.quantity=next;saveCart();ecommerce(diff>0?'add_to_cart':'remove_from_cart',[item(p,Math.abs(diff))]);renderCart(); }
function art(p,extra='') { return `<div class="product-art art-${p.art} ${extra}" role="img" aria-label="${p.item_name} demo product"></div>`; }
function cards(list,container,listName) {
 container.innerHTML=list.map(p=>`<article class="product-card">${art(p).replace('</div>',`<span class="badge">${p.tag}</span></div>`)}<div class="card-info"><div class="category">${p.item_category}</div><h3>${p.item_name}</h3><div class="price">${money(p.price)}<span class="old-price">${money(p.old)}</span></div><div class="card-actions"><button id="view-${p.item_id}" class="btn secondary" data-view="${p.item_id}" data-list="${listName}">View Product</button><button id="add-${p.item_id}" class="btn" data-add="${p.item_id}">+ Add to Cart</button></div><small class="practice">select_item · add_to_cart</small></div></article>`).join('');
 if(list.length)ecommerce('view_item_list',list.map(p=>item(p)),{item_list_name:listName,item_list_id:listName==='Featured products'?'featured':'catalog'});
}
let currentProduct;
function openProduct(id,listName='Products') { currentProduct=PRODUCTS.find(p=>p.item_id===id);if(!currentProduct)return;const p=currentProduct;ecommerce('select_item',[item(p)],{item_list_name:listName});ecommerce('view_item',[item(p)]);$('#product-detail').innerHTML=`<div class="detail-layout">${art(p)}<div><div class="category">${p.item_category}</div><h2 id="product-title">${p.item_name}</h2><div class="price">${money(p.price)}</div><p style="margin-top:15px">${p.description}</p><label for="product-quantity">Quantity</label><div class="qty"><button id="product-minus" aria-label="Decrease quantity" type="button">−</button><input id="product-quantity" type="number" min="1" max="99" value="1"><button id="product-plus" aria-label="Increase quantity" type="button">+</button></div><div class="actions"><button id="btn-add-cart" class="btn">Add to Cart</button><button id="btn-buy-now" class="btn secondary">Buy Now →</button></div><small class="practice">add_to_cart · begin_checkout</small></div></div>`;$('#product-modal').showModal();
 const quantity=$('#product-quantity'); const update=n=>{quantity.value=Math.max(1,Math.min(99,Math.floor(Number(n)||1)));track('product_interaction',{interaction:'quantity_change',item_id:id,quantity:Number(quantity.value)});};$('#product-minus').onclick=()=>update(+quantity.value-1);$('#product-plus').onclick=()=>update(+quantity.value+1);quantity.onchange=()=>update(quantity.value);$('#btn-add-cart').onclick=()=>addCart(id,+quantity.value);$('#btn-buy-now').onclick=()=>{track('product_interaction',{interaction:'buy_now',item_id:id});if(addCart(id,+quantity.value,true))location.href='checkout.html';};
}
$('#close-product').onclick=()=>$('#product-modal').close();
$('#product-modal').addEventListener('close',()=>{if(currentProduct)track('product_interaction',{interaction:'close_product',item_id:currentProduct.item_id});});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addCart(add.dataset.add);const view=e.target.closest('[data-view]');if(view)openProduct(view.dataset.view,view.dataset.list);const nav=e.target.closest('[data-nav]');if(nav)track('navigation_click',{link_text:nav.dataset.nav,link_url:nav.getAttribute('href')});const cta=e.target.closest('[data-cta]');if(cta){track('cta_click',{cta_name:cta.dataset.cta,element_id:cta.id});track('custom_cta_click',{cta_name:cta.dataset.cta,element_id:cta.id});}});
$('#menu-toggle').onclick=()=>{const open=$('.navlinks').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));};
$('#search-form').addEventListener('submit',e=>{e.preventDefault();const term=$('#search-input').value.trim();if(!term){$('#search-input').focus();return;}track('search',{search_term:term});location.href='products.html?q='+encodeURIComponent(term);});
$('#download-brochure').onclick=()=>{track('download_click',{file_name:'trackshop-brochure.txt',file_extension:'txt',link_id:'download-brochure'});track('file_download',{file_name:'trackshop-brochure.txt',file_extension:'txt',link_id:'download-brochure'});};
$('#external-link').onclick=()=>track('outbound_click',{link_url:$('#external-link').href,link_domain:'instagram.com',outbound:true});
// Form metadata only: NEVER put names, addresses, emails, phone numbers, or field values in analytics.
$$('form:not(#search-form)').forEach(form=>{let started=false;form.addEventListener('focusin',e=>{if(e.target.matches('input,textarea,select')&&!started){track('form_start',{form_id:form.id});started=true;}});form.addEventListener('change',e=>{if(e.target.id)track('form_interaction',{form_id:form.id,field_id:e.target.id});});});
if(page==='index'){
 cards(PRODUCTS.slice(0,4),$('#featured-products'),'Featured products');
 $('#newsletter-form').onsubmit=e=>{e.preventDefault();track('form_submit',{form_id:'newsletter-form'});track('sign_up',{method:'newsletter'});$('#newsletter-status').textContent='You’re on the demo list! No email was sent.';e.target.reset();};
 let videoStarted=false,videoDone=false,videoPercent=0;const milestones=new Set();
 $$('[data-video]').forEach(button=>button.onclick=()=>{const action=button.dataset.video;const base={video_title:'Every move tells a story',video_provider:'simulator',video_duration:100};const start=()=>{videoStarted=true;videoDone=false;videoPercent=0;milestones.clear();track('video_start',{...base,video_percent:0,video_current_time:0});};if(action==='play'){if(!videoStarted||videoDone)start();else track('video_resume',{...base,video_percent:videoPercent,video_current_time:videoPercent});$('#video-state').textContent=`Playing · ${videoPercent}%`;}else if(action==='pause'){if(!videoStarted||videoDone){toast('Press Play to start a video simulation.');return;}track('video_pause',{...base,video_percent:videoPercent,video_current_time:videoPercent});$('#video-state').textContent=`Paused · ${videoPercent}%`;}else{if(!videoStarted){toast('Press Play first, then try a milestone.');return;}const value=action==='complete'?100:Number(action);if(videoDone||value<=videoPercent){toast('This milestone is already passed. Complete and press Play to restart.');return;}[25,50,75].filter(n=>n<=value&&!milestones.has(n)).forEach(n=>{milestones.add(n);track('video_progress',{...base,video_percent:n,video_current_time:n});});videoPercent=value;if(value===100){videoDone=true;track('video_complete',{...base,video_percent:100,video_current_time:100});}$('#video-state').textContent=`${videoDone?'Complete':'Playing'} · ${value}%`;}$('#video-progress').value=videoPercent;});
 async function copyCoupon(){try{await navigator.clipboard.writeText('TRACK10');toast('Copied TRACK10 — use it at checkout');}catch{toast('Your coupon is TRACK10');}track('copy_coupon',{coupon:'TRACK10'});}
 $('#offer-copy-coupon').onclick=copyCoupon;
 $$('[data-play]').forEach(button=>button.onclick=async()=>{track('custom_cta_click',{cta_name:button.dataset.play,element_id:button.id});const output=$('#playground-output');switch(button.id){case 'copy-coupon':await copyCoupon();break;case 'open-popup':$('#playground-modal').showModal();track('popup_open',{popup_id:'playground-modal'});break;case 'show-phone':output.textContent='Demo phone: +91 00000 00000';track('phone_reveal',{element_id:button.id});break;case 'show-email':output.textContent='Demo email: hello@trackshop.example';track('email_reveal',{element_id:button.id});break;case 'share-product':{const url=new URL('products.html?product=SKU001',location.href).href;try{if(navigator.share){await navigator.share({title:'TrackShop Running Shoes',url});track('share',{method:'native',content_type:'product',item_id:'SKU001'});output.textContent='Product shared.';}else{await navigator.clipboard.writeText(url);track('share',{method:'copy_link',content_type:'product',item_id:'SKU001'});output.textContent='Product link copied.';}}catch(err){if(err.name!=='AbortError'){output.textContent='Product link: '+url;track('share_link_shown',{item_id:'SKU001'});}}break;}case 'get-quote':output.textContent='Demo quote requested. Explore your custom_cta_click event.';track('quote_requested',{source:'playground'});break;case 'book-demo':output.textContent='Demo booking recorded locally. No meeting has been scheduled.';track('demo_requested',{source:'playground'});break;default:output.textContent='Click captured! Take a look in the debug panel.';}});
 $('#close-popup').onclick=()=>$('#playground-modal').close();$('#playground-modal').addEventListener('close',()=>{track('popup_close',{popup_id:'playground-modal'});track('custom_cta_click',{cta_name:'Close Popup',element_id:'close-popup'});});
}
if(page==='products') {const params=new URLSearchParams(location.search);const query=(params.get('q')||'').trim();$('#search-input').value=query;let category='All products';function filter(){const list=PRODUCTS.filter(p=>(category==='All products'||p.item_category===category)&&p.item_name.toLowerCase().includes(query.toLowerCase()));$('#search-status').textContent=query?`${list.length} results for “${query}”`:`Showing ${list.length} products`;cards(list,$('#product-grid'),'Product catalog');if(!list.length)$('#product-grid').innerHTML='<div class="empty"><h2>No products found</h2><p>Try shoes, watch, backpack, headphones, t-shirt, or water bottle.</p><a id="reset-search" class="btn secondary" href="products.html">See all products</a></div>';};$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;$$('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});track('product_filter',{category});filter();});filter();if(params.has('product'))openProduct(params.get('product'),'Shared product');}
function summaryHTML(items,discount=false){const subtotal=sum(cartItems());const total=sum(items);return `<h2>Order summary</h2>${items.map(p=>`<div class="summary-line"><span>${p.item_name} × ${p.quantity}</span><strong>${money(p.price*p.quantity)}</strong></div>`).join('')}<div class="summary-line"><span>Subtotal</span><span>${money(subtotal)}</span></div>${discount?`<div class="summary-line"><span>TRACK10 · 10% off</span><span>−${money(subtotal-total)}</span></div>`:''}<div class="summary-line"><span>Demo shipping</span><span>Free</span></div><div class="summary-line total"><span>Total</span><span>${money(total)}</span></div><p class="small">INR · Demo products. No actual payment.</p>`;}
function renderCart(){if(page!=='cart')return;$('#cart-items').innerHTML=cart.length?cart.map(row=>{const p=PRODUCTS.find(p=>p.item_id===row.id);return `<div class="cart-row">${art(p)}<div><h3>${p.item_name}</h3><p>${p.item_category} · ${money(p.price)} each</p><div class="qty"><button id="minus-${p.item_id}" data-quantity="${p.item_id}" data-next="${row.quantity-1}" aria-label="Decrease ${p.item_name} quantity">−</button><input id="qty-${p.item_id}" data-cart-qty="${p.item_id}" aria-label="${p.item_name} quantity" type="number" min="1" max="99" value="${row.quantity}"><button id="plus-${p.item_id}" data-quantity="${p.item_id}" data-next="${row.quantity+1}" aria-label="Increase ${p.item_name} quantity">+</button></div></div><div><strong>${money(p.price*row.quantity)}</strong><br><button id="remove-${p.item_id}" class="remove" data-quantity="${p.item_id}" data-next="0">Remove</button></div></div>`;}).join(''):'<div class="empty"><h2>Your cart is a blank canvas.</h2><p>Add your first product to begin the ecommerce tracking journey.</p><a id="empty-cart-shop" href="products.html" class="btn">Explore products →</a></div>';$('#cart-summary').innerHTML=summaryHTML(cartItems())+(cart.length?'<a id="proceed-checkout" href="checkout.html" class="btn">Proceed to Checkout →</a><small class="practice">Practice event: begin_checkout</small>':'');$$('[data-quantity]').forEach(b=>b.onclick=()=>changeQuantity(b.dataset.quantity,+b.dataset.next));$$('[data-cart-qty]').forEach(input=>input.onchange=()=>changeQuantity(input.dataset.cartQty,+input.value));}
if(page==='cart'){renderCart();ecommerce('view_cart',cartItems());}
if(page==='checkout') {
 let discount=false,shippingConfirmed=false,placing=false;const form=$('#checkout-form');const shipping=$$('[id^="checkout-"]',form).filter(x=>x.matches('input'));
 function redraw(){$('#checkout-summary').innerHTML=summaryHTML(cartItems(discount),discount);}
 function confirmShipping(){for(const field of shipping){if(!field.reportValidity())return false;}if(!shippingConfirmed){ecommerce('add_shipping_info',cartItems(discount),{shipping_tier:'Free demo shipping',...(discount?{coupon:'TRACK10'}:{})});shippingConfirmed=true;}$('#shipping-status').textContent='Demo shipping confirmed.';return true;}
 if(!cart.length){form.innerHTML='<div class="empty"><h2>Your cart is empty.</h2><p>Add a product before starting a demo checkout.</p><a id="empty-checkout-shop" class="btn" href="products.html">Browse products →</a></div>';redraw();}
 else {ecommerce('begin_checkout',cartItems());redraw();shipping.forEach(input=>input.addEventListener('input',()=>{shippingConfirmed=false;$('#shipping-status').textContent='';}));$('#confirm-shipping').onclick=confirmShipping;$('#apply-coupon').onclick=()=>{const valid=$('#coupon-code').value.trim().toUpperCase()==='TRACK10';if(valid){if(!discount){discount=true;track('coupon_applied',{coupon:'TRACK10',discount_value:round(sum(cartItems())-sum(cartItems(true))),currency:'INR'});}$('#coupon-status').textContent='TRACK10 applied — 10% off your demo order.';}else{$('#coupon-status').textContent=discount?'That code is not valid. TRACK10 remains applied.':'Try TRACK10 for 10% off.';track('coupon_invalid',{form_id:'checkout-form'});}redraw();};$$('[name="payment"]').forEach(input=>input.onchange=()=>ecommerce('add_payment_info',cartItems(discount),{payment_type:input.value,...(discount?{coupon:'TRACK10'}:{})}));form.onsubmit=e=>{e.preventDefault();if(placing||!cart.length||!form.reportValidity()||!confirmShipping())return;placing=true;$('#place-order').disabled=true;track('form_submit',{form_id:'checkout-form'});const purchased=cartItems(discount);const order={transaction_id:'TS-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),items:purchased,value:sum(purchased),currency:'INR',shipping:0,tax:0,...(discount?{coupon:'TRACK10'}:{})};
 // Save product data only. No buyer name, email, phone, city, or address.
 if(!saveStorage('trackshop-order',order)){placing=false;$('#place-order').disabled=false;$('#checkout-status').textContent='Allow browser storage to complete this demo order.';return;}cart=[];saveCart();location.href='thank-you.html';};}
}
if(page==='thank-you') {const order=readStorage('trackshop-order',null);const valid=order&&typeof order.transaction_id==='string'&&Array.isArray(order.items)&&order.items.every(p=>p&&typeof p.item_name==='string'&&Number.isFinite(p.price)&&Number.isInteger(p.quantity))&&Number.isFinite(order.value);if(!valid){$('#confirmation').innerHTML='<div class="empty"><h1>No demo order yet.</h1><p>Complete checkout to see your confirmation and purchase event.</p><a id="no-order-shop" class="btn" href="products.html">Browse products →</a></div>';}else{$('#confirmation').innerHTML=`<div class="success-icon">✓</div><div class="eyebrow" style="justify-content:center">DEMO ORDER COMPLETE</div><h1>Thanks for checking out.</h1><p>Your pretend order is confirmed. Your next insight is waiting.</p><div class="notice">No real purchase or payment was made.</div><div class="summary"><h2>Order ${escapeHTML(order.transaction_id)}</h2>${order.items.map(p=>`<div class="summary-line"><span>${escapeHTML(p.item_name)} × ${p.quantity}</span><strong>${money(p.price*p.quantity)}</strong></div>`).join('')}${order.coupon?'<p class="small">TRACK10 · 10% discount included</p>':''}<div class="summary-line total"><span>Total</span><span>${money(order.value)}</span></div></div><a id="continue-shopping-thanks" href="products.html" class="btn">Continue Shopping →</a><small class="practice">Practice event: purchase · ${escapeHTML(order.transaction_id)}</small>`;
 // Persist the transaction guard across reloads/back navigation. Start another
 // checkout to create a new transaction. Clearing browser storage resets it.
 let sent=readStorage('trackshop-purchases',[]);if(!Array.isArray(sent))sent=[];if(!sent.includes(order.transaction_id)){window.dataLayer.push({ecommerce:null});track('purchase',{ecommerce:order});sent.push(order.transaction_id);saveStorage('trackshop-purchases',sent.slice(-200));}}
}
if(page==='contact')$('#contact-form').onsubmit=e=>{e.preventDefault();track('form_submit',{form_id:'contact-form'});track('generate_lead',{form_id:'contact-form',lead_source:'demo_contact'});$('#contact-status').textContent='Thank you. Your enquiry has been submitted.';e.target.reset();};
if(page==='about'){const seen=new Set();function scrollDepth(){const distance=document.documentElement.scrollHeight-window.innerHeight;if(distance<=0)return;const percent=Math.min(100,Math.round(window.scrollY/distance*100));[25,50,75,90].forEach(value=>{if(percent>=value&&!seen.has(value)){seen.add(value);track('scroll_depth',{percent_scrolled:value,page_name:'About'});}});}window.addEventListener('scroll',scrollDepth,{passive:true});scrollDepth();}
updateCount();
